#!/usr/bin/env bash
if [ "$2" == "clone" ]; then
  git clone git@github.com:lucaspaiva1/DockerMagento2.git $1 && cd $1;
fi

git config --global core.autocrlf false
git config --global core.eol LF
git config --global core.fileMode false
git config --global diff.renamelimit 5000

sudo chmod u+x ./*

docker image pull lucaspaiva1/magento24

if [ "$(uname)" == "Darwin" ]; then
  git checkout -f mac;
  sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml \
  && sed -i '' -e "s/<project_name>/$1/g" docker-compose-dev.yml \
  && sed -i '' -e "s/<project_name>/$1/g" docker-sync.yml
else
  git checkout -f master;
  sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml;
fi

bash start
